package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Alternativas generated by hbm2java
 */
public class Alternativas  implements java.io.Serializable {


     private int idAlternativa;
     private Pregunta pregunta;
     private int puntaje;
     private Boolean correcta;
     private String textoAlternativa;

     
    public Alternativas() {
    }


    
    
    public String getTextoAlternativa() {
        return textoAlternativa;
    }

    public void setTextoAlternativa(String textoAlternativa) {
        this.textoAlternativa = textoAlternativa;
    }

	
    public Alternativas(int idAlternativa, Pregunta pregunta, int puntaje) {
        this.idAlternativa = idAlternativa;
        this.pregunta = pregunta;
        this.puntaje = puntaje;
    }
    public Alternativas(int idAlternativa, Pregunta pregunta, int puntaje, Boolean correcta) {
       this.idAlternativa = idAlternativa;
       this.pregunta = pregunta;
       this.puntaje = puntaje;
       this.correcta = correcta;
    }
   
    public int getIdAlternativa() {
        return this.idAlternativa;
    }
    
    public void setIdAlternativa(int idAlternativa) {
        this.idAlternativa = idAlternativa;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public Boolean getCorrecta() {
        return this.correcta;
    }
    
    public void setCorrecta(Boolean correcta) {
        this.correcta = correcta;
    }




}


