package model.entities;
// Generated 27-may-2015 14:38:52 by Hibernate Tools 4.3.1



/**
 * Alternativas generated by hbm2java
 */
public class Alternativas  implements java.io.Serializable {


     private Integer idalternativa;
     private Pregunta pregunta;
     private Integer puntaje;
     private Character correcta;
     private String textoalternativa;

    public Alternativas() {
    }

	
    public Alternativas(Pregunta pregunta, Integer puntaje, String textoalternativa) {
        this.pregunta = pregunta;
        this.puntaje = puntaje;
        this.textoalternativa = textoalternativa;
    }
    public Alternativas(Pregunta pregunta, Integer puntaje, Character correcta, String textoalternativa) {
       this.pregunta = pregunta;
       this.puntaje = puntaje;
       this.correcta = correcta;
       this.textoalternativa = textoalternativa;
    }
   
    public Integer getIdalternativa() {
        return this.idalternativa;
    }
    
    public void setIdalternativa(Integer idalternativa) {
        this.idalternativa = idalternativa;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }
    public Character getCorrecta() {
        return this.correcta;
    }
    
    public void setCorrecta(Character correcta) {
        this.correcta = correcta;
    }
    public String getTextoalternativa() {
        return this.textoalternativa;
    }
    
    public void setTextoalternativa(String textoalternativa) {
        this.textoalternativa = textoalternativa;
    }




}


