package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Encuestador generated by hbm2java
 */
public class Encuestador  implements java.io.Serializable {


     private int idEncuestador;
     private String nombre;
     private String rut;
     private String apellido;
     private String nick;
     private String contrasena;
     private String email;
     private Set plantillas = new HashSet(0);
     private Set evaluacions = new HashSet(0);

    public Encuestador() {
    }

    public String getRut() {
        return rut;
    }

    public void setRut(String rut) {
        this.rut = rut;
    }

    
	
    public Encuestador(int idEncuestador, String nombre, String apellido, String nick, String contrasena, String email) {
        this.idEncuestador = idEncuestador;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nick = nick;
        this.contrasena = contrasena;
        this.email = email;
    }
    public Encuestador(int idEncuestador, String nombre, String apellido, String nick, String contrasena, String email, Set plantillas, Set evaluacions) {
       this.idEncuestador = idEncuestador;
       this.nombre = nombre;
       this.apellido = apellido;
       this.nick = nick;
       this.contrasena = contrasena;
       this.email = email;
       this.plantillas = plantillas;
       this.evaluacions = evaluacions;
    }
   
    public int getIdEncuestador() {
        return this.idEncuestador;
    }
    
    public void setIdEncuestador(int idEncuestador) {
        this.idEncuestador = idEncuestador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPlantillas() {
        return this.plantillas;
    }
    
    public void setPlantillas(Set plantillas) {
        this.plantillas = plantillas;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


