package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Encuestado generated by hbm2java
 */
public class Encuestado  implements java.io.Serializable {


     private int idEncuestado;
     private String apellido;
     private String nombre;
     private String curso;
     private String sexo;
     private String email;
     private String nivel;
     private String colegio;
     private Set tests = new HashSet(0);

    public Encuestado() {
    }

	
    public Encuestado(int idEncuestado, String apellido, String nombre) {
        this.idEncuestado = idEncuestado;
        this.apellido = apellido;
        this.nombre = nombre;
    }
    public Encuestado(int idEncuestado, String apellido, String nombre, String curso, String sexo, String email, String nivel, String colegio, Set tests) {
       this.idEncuestado = idEncuestado;
       this.apellido = apellido;
       this.nombre = nombre;
       this.curso = curso;
       this.sexo = sexo;
       this.email = email;
       this.nivel = nivel;
       this.colegio = colegio;
       this.tests = tests;
    }
   
    public int getIdEncuestado() {
        return this.idEncuestado;
    }
    
    public void setIdEncuestado(int idEncuestado) {
        this.idEncuestado = idEncuestado;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public Set getTests() {
        return this.tests;
    }
    
    public void setTests(Set tests) {
        this.tests = tests;
    }




}


