package model.entities;
// Generated 27-may-2015 14:38:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encuestador generated by hbm2java
 */
public class Encuestador  implements java.io.Serializable {


     private Integer idencuestador;
     private String nombre;
     private String apellido;
     private String nick;
     private String contrasena;
     private String email;
     private String rut;
     private Set evaluacions = new HashSet(0);
     private Set plantillas = new HashSet(0);
     private Set roleses = new HashSet(0);

    public Encuestador() {
    }

	
    public Encuestador(Integer idencuestador, String nombre, String apellido, String nick, String contrasena, String email, String rut) {
        this.idencuestador = idencuestador;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nick = nick;
        this.contrasena = contrasena;
        this.email = email;
        this.rut = rut;
    }
    public Encuestador(Integer idencuestador, String nombre, String apellido, String nick, String contrasena, String email, String rut, Set evaluacions, Set plantillas, Set roleses) {
       this.idencuestador = idencuestador;
       this.nombre = nombre;
       this.apellido = apellido;
       this.nick = nick;
       this.contrasena = contrasena;
       this.email = email;
       this.rut = rut;
       this.evaluacions = evaluacions;
       this.plantillas = plantillas;
       this.roleses = roleses;
    }
   
    public Integer getIdencuestador() {
        return this.idencuestador;
    }
    
    public void setIdencuestador(Integer idencuestador) {
        this.idencuestador = idencuestador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }
    public Set getPlantillas() {
        return this.plantillas;
    }
    
    public void setPlantillas(Set plantillas) {
        this.plantillas = plantillas;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }




}


