package model.entities;
// Generated 01-12-2014 01:13:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evaluacionpreguntas generated by hbm2java
 */
public class Evaluacionpreguntas  implements java.io.Serializable {


     private EvaluacionpreguntasId id;
     private Pregunta pregunta;
     private Evaluacion evaluacion;
     private Date fechaHora;
     private Set tests = new HashSet(0);

    public Evaluacionpreguntas() {
    }

	
    public Evaluacionpreguntas(EvaluacionpreguntasId id, Pregunta pregunta, Evaluacion evaluacion) {
        this.id = id;
        this.pregunta = pregunta;
        this.evaluacion = evaluacion;
    }
    public Evaluacionpreguntas(EvaluacionpreguntasId id, Pregunta pregunta, Evaluacion evaluacion, Date fechaHora, Set tests) {
       this.id = id;
       this.pregunta = pregunta;
       this.evaluacion = evaluacion;
       this.fechaHora = fechaHora;
       this.tests = tests;
    }
   
    public EvaluacionpreguntasId getId() {
        return this.id;
    }
    
    public void setId(EvaluacionpreguntasId id) {
        this.id = id;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Set getTests() {
        return this.tests;
    }
    
    public void setTests(Set tests) {
        this.tests = tests;
    }




}


