package model.entities;
// Generated 01-12-2014 01:13:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private Integer idEvaluacion;
     private Encuestador encuestador;
     private Plantilla plantilla;
     private String item;
     private String cabecera;
     private String mensajeConfirmacion;
     private String piePagina;
     private Set evaluacionpreguntases = new HashSet(0);

    public Evaluacion() {
    }

	
    public Evaluacion(Encuestador encuestador, Plantilla plantilla, String cabecera, String piePagina) {
        this.encuestador = encuestador;
        this.plantilla = plantilla;
        this.cabecera = cabecera;
        this.piePagina = piePagina;
    }
    public Evaluacion(Encuestador encuestador, Plantilla plantilla, String item, String cabecera, String mensajeConfirmacion, String piePagina, Set evaluacionpreguntases) {
       this.encuestador = encuestador;
       this.plantilla = plantilla;
       this.item = item;
       this.cabecera = cabecera;
       this.mensajeConfirmacion = mensajeConfirmacion;
       this.piePagina = piePagina;
       this.evaluacionpreguntases = evaluacionpreguntases;
    }
   
    public Integer getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(Integer idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public Encuestador getEncuestador() {
        return this.encuestador;
    }
    
    public void setEncuestador(Encuestador encuestador) {
        this.encuestador = encuestador;
    }
    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla plantilla) {
        this.plantilla = plantilla;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getCabecera() {
        return this.cabecera;
    }
    
    public void setCabecera(String cabecera) {
        this.cabecera = cabecera;
    }
    public String getMensajeConfirmacion() {
        return this.mensajeConfirmacion;
    }
    
    public void setMensajeConfirmacion(String mensajeConfirmacion) {
        this.mensajeConfirmacion = mensajeConfirmacion;
    }
    public String getPiePagina() {
        return this.piePagina;
    }
    
    public void setPiePagina(String piePagina) {
        this.piePagina = piePagina;
    }
    public Set getEvaluacionpreguntases() {
        return this.evaluacionpreguntases;
    }
    
    public void setEvaluacionpreguntases(Set evaluacionpreguntases) {
        this.evaluacionpreguntases = evaluacionpreguntases;
    }




}


