package model.entities;
// Generated 01-12-2014 01:13:15 AM by Hibernate Tools 3.2.1.GA



/**
 * EvaluacionpreguntasId generated by hbm2java
 */
public class EvaluacionpreguntasId  implements java.io.Serializable {


     private int idPregunta;
     private int idEvaluacion;

    public EvaluacionpreguntasId() {
    }

    public EvaluacionpreguntasId(int idPregunta, int idEvaluacion) {
       this.idPregunta = idPregunta;
       this.idEvaluacion = idEvaluacion;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluacionpreguntasId) ) return false;
		 EvaluacionpreguntasId castOther = ( EvaluacionpreguntasId ) other; 
         
		 return (this.getIdPregunta()==castOther.getIdPregunta())
 && (this.getIdEvaluacion()==castOther.getIdEvaluacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPregunta();
         result = 37 * result + this.getIdEvaluacion();
         return result;
   }   


}


