package model.entities;
// Generated 14-may-2015 17:53:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EvapreguntasId generated by hbm2java
 */
public class EvapreguntasId  implements java.io.Serializable {


     private Integer preguntaId;
     private Integer evaluacionId;

    public EvapreguntasId() {
    }

    public EvapreguntasId(Integer preguntaId, Integer evaluacionId) {
       this.preguntaId = preguntaId;
       this.evaluacionId = evaluacionId;
    }
   
    public Integer getPreguntaId() {
        return this.preguntaId;
    }
    
    public void setPreguntaId(Integer preguntaId) {
        this.preguntaId = preguntaId;
    }
    public Integer getEvaluacionId() {
        return this.evaluacionId;
    }
    
    public void setEvaluacionId(Integer evaluacionId) {
        this.evaluacionId = evaluacionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvapreguntasId) ) return false;
		 EvapreguntasId castOther = ( EvapreguntasId ) other; 
         
		 return ( (this.getPreguntaId()==castOther.getPreguntaId()) || ( this.getPreguntaId()!=null && castOther.getPreguntaId()!=null && this.getPreguntaId().equals(castOther.getPreguntaId()) ) )
 && ( (this.getEvaluacionId()==castOther.getEvaluacionId()) || ( this.getEvaluacionId()!=null && castOther.getEvaluacionId()!=null && this.getEvaluacionId().equals(castOther.getEvaluacionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPreguntaId() == null ? 0 : this.getPreguntaId().hashCode() );
         result = 37 * result + ( getEvaluacionId() == null ? 0 : this.getEvaluacionId().hashCode() );
         return result;
   }   


}


