package model.Entities;
// Generated 27-abr-2015 12:45:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evapreguntas generated by hbm2java
 */
public class Evapreguntas  implements java.io.Serializable {


     private EvapreguntasId id;
     private Evaluacion evaluacion;
     private Pregunta pregunta;
     private Date fechahora;
private Set respuestas = new HashSet(0);
    public Evapreguntas() {
    }

	
    public Evapreguntas(EvapreguntasId id, Evaluacion evaluacion, Pregunta pregunta) {
        this.id = id;
        this.evaluacion = evaluacion;
        this.pregunta = pregunta;
    }
    public Evapreguntas(EvapreguntasId id, Evaluacion evaluacion, Pregunta pregunta, Date fechahora) {
       this.id = id;
       this.evaluacion = evaluacion;
       this.pregunta = pregunta;
       this.fechahora = fechahora;
    }
   
    
        public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }

    public EvapreguntasId getId() {
        return this.id;
    }
    
    public void setId(EvapreguntasId id) {
        this.id = id;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }




}


