package model.entities;
// Generated 14-may-2015 17:53:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Grupopreguntas generated by hbm2java
 */
public class Grupopreguntas  implements java.io.Serializable {


     private Integer id;
     private String descripciongrupo;
     private Set preguntas = new HashSet(0);

    public Grupopreguntas() {
    }

	
    public Grupopreguntas(Integer id, String descripciongrupo) {
        this.id = id;
        this.descripciongrupo = descripciongrupo;
    }
    public Grupopreguntas(Integer id, String descripciongrupo, Set preguntas) {
       this.id = id;
       this.descripciongrupo = descripciongrupo;
       this.preguntas = preguntas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripciongrupo() {
        return this.descripciongrupo;
    }
    
    public void setDescripciongrupo(String descripciongrupo) {
        this.descripciongrupo = descripciongrupo;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


