package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Grupopreguntas generated by hbm2java
 */
public class Grupopreguntas  implements java.io.Serializable {


     private int idGrupoPreguntas;
     private String descripcionGrupo;
     private Set preguntas = new HashSet(0);

    public Grupopreguntas() {
    }

	
    public Grupopreguntas(int idGrupoPreguntas, String descripcionGrupo) {
        this.idGrupoPreguntas = idGrupoPreguntas;
        this.descripcionGrupo = descripcionGrupo;
    }
    public Grupopreguntas(int idGrupoPreguntas, String descripcionGrupo, Set preguntas) {
       this.idGrupoPreguntas = idGrupoPreguntas;
       this.descripcionGrupo = descripcionGrupo;
       this.preguntas = preguntas;
    }
   
    public int getIdGrupoPreguntas() {
        return this.idGrupoPreguntas;
    }
    
    public void setIdGrupoPreguntas(int idGrupoPreguntas) {
        this.idGrupoPreguntas = idGrupoPreguntas;
    }
    public String getDescripcionGrupo() {
        return this.descripcionGrupo;
    }
    
    public void setDescripcionGrupo(String descripcionGrupo) {
        this.descripcionGrupo = descripcionGrupo;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


