package model.entities;
// Generated 27-may-2015 14:38:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plantilla generated by hbm2java
 */
public class Plantilla  implements java.io.Serializable {


     private Integer idplantilla;
     private Encuestador encuestador;
     private String tipo;
     private String descripcion;
     private Set evaluacions = new HashSet(0);

    public Plantilla() {
    }

	
    public Plantilla(Integer idplantilla, String tipo, String descripcion) {
        this.idplantilla = idplantilla;
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public Plantilla(Integer idplantilla, Encuestador encuestador, String tipo, String descripcion, Set evaluacions) {
       this.idplantilla = idplantilla;
       this.encuestador = encuestador;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.evaluacions = evaluacions;
    }
   
    public Integer getIdplantilla() {
        return this.idplantilla;
    }
    
    public void setIdplantilla(Integer idplantilla) {
        this.idplantilla = idplantilla;
    }
    public Encuestador getEncuestador() {
        return this.encuestador;
    }
    
    public void setEncuestador(Encuestador encuestador) {
        this.encuestador = encuestador;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


