package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Plantilla generated by hbm2java
 */
public class Plantilla  implements java.io.Serializable {


     private int idPlantilla;
     private Encuestador encuestador;
     private String tipo;
     private String descripcion;
     private Set evaluacions = new HashSet(0);

    public Plantilla() {
    }

	
    public Plantilla(int idPlantilla, String tipo, String descripcion) {
        this.idPlantilla = idPlantilla;
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public Plantilla(int idPlantilla, Encuestador encuestador, String tipo, String descripcion, Set evaluacions) {
       this.idPlantilla = idPlantilla;
       this.encuestador = encuestador;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.evaluacions = evaluacions;
    }
   
    public int getIdPlantilla() {
        return this.idPlantilla;
    }
    
    public void setIdPlantilla(int idPlantilla) {
        this.idPlantilla = idPlantilla;
    }
    public Encuestador getEncuestador() {
        return this.encuestador;
    }
    
    public void setEncuestador(Encuestador encuestador) {
        this.encuestador = encuestador;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


