package model.entities;
// Generated 27-may-2015 14:38:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Integer id;
     private Grupopreguntas grupopreguntas;
     private String textopregunta;
     private String tipopregunta;
     private char obligatorio;
     private Set evapreguntases = new HashSet(0);
     private Set alternativases = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(Grupopreguntas grupopreguntas, String textopregunta, String tipopregunta, char obligatorio) {
        this.grupopreguntas = grupopreguntas;
        this.textopregunta = textopregunta;
        this.tipopregunta = tipopregunta;
        this.obligatorio = obligatorio;
    }
    public Pregunta(Grupopreguntas grupopreguntas, String textopregunta, String tipopregunta, char obligatorio, Set evapreguntases, Set alternativases) {
       this.grupopreguntas = grupopreguntas;
       this.textopregunta = textopregunta;
       this.tipopregunta = tipopregunta;
       this.obligatorio = obligatorio;
       this.evapreguntases = evapreguntases;
       this.alternativases = alternativases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Grupopreguntas getGrupopreguntas() {
        return this.grupopreguntas;
    }
    
    public void setGrupopreguntas(Grupopreguntas grupopreguntas) {
        this.grupopreguntas = grupopreguntas;
    }
    public String getTextopregunta() {
        return this.textopregunta;
    }
    
    public void setTextopregunta(String textopregunta) {
        this.textopregunta = textopregunta;
    }
    public String getTipopregunta() {
        return this.tipopregunta;
    }
    
    public void setTipopregunta(String tipopregunta) {
        this.tipopregunta = tipopregunta;
    }
    public char getObligatorio() {
        return this.obligatorio;
    }
    
    public void setObligatorio(char obligatorio) {
        this.obligatorio = obligatorio;
    }
    public Set getEvapreguntases() {
        return this.evapreguntases;
    }
    
    public void setEvapreguntases(Set evapreguntases) {
        this.evapreguntases = evapreguntases;
    }
    public Set getAlternativases() {
        return this.alternativases;
    }
    
    public void setAlternativases(Set alternativases) {
        this.alternativases = alternativases;
    }




}


