package model.entities;
// Generated 28-abr-2015 16:50:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RespuestaId generated by hbm2java
 */
public class RespuestaId  implements java.io.Serializable {


     private Integer testIdtest;
     private Integer evapreguntasPreguntaId;
     private Integer evapreguntasEvaluacionId;

    public RespuestaId() {
    }

    public RespuestaId(Integer testIdtest, Integer evapreguntasPreguntaId, Integer evapreguntasEvaluacionId) {
       this.testIdtest = testIdtest;
       this.evapreguntasPreguntaId = evapreguntasPreguntaId;
       this.evapreguntasEvaluacionId = evapreguntasEvaluacionId;
    }
   
    public Integer getTestIdtest() {
        return this.testIdtest;
    }
    
    public void setTestIdtest(Integer testIdtest) {
        this.testIdtest = testIdtest;
    }
    public Integer getEvapreguntasPreguntaId() {
        return this.evapreguntasPreguntaId;
    }
    
    public void setEvapreguntasPreguntaId(Integer evapreguntasPreguntaId) {
        this.evapreguntasPreguntaId = evapreguntasPreguntaId;
    }
    public Integer getEvapreguntasEvaluacionId() {
        return this.evapreguntasEvaluacionId;
    }
    
    public void setEvapreguntasEvaluacionId(Integer evapreguntasEvaluacionId) {
        this.evapreguntasEvaluacionId = evapreguntasEvaluacionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RespuestaId) ) return false;
		 RespuestaId castOther = ( RespuestaId ) other; 
         
		 return ( (this.getTestIdtest()==castOther.getTestIdtest()) || ( this.getTestIdtest()!=null && castOther.getTestIdtest()!=null && this.getTestIdtest().equals(castOther.getTestIdtest()) ) )
 && ( (this.getEvapreguntasPreguntaId()==castOther.getEvapreguntasPreguntaId()) || ( this.getEvapreguntasPreguntaId()!=null && castOther.getEvapreguntasPreguntaId()!=null && this.getEvapreguntasPreguntaId().equals(castOther.getEvapreguntasPreguntaId()) ) )
 && ( (this.getEvapreguntasEvaluacionId()==castOther.getEvapreguntasEvaluacionId()) || ( this.getEvapreguntasEvaluacionId()!=null && castOther.getEvapreguntasEvaluacionId()!=null && this.getEvapreguntasEvaluacionId().equals(castOther.getEvapreguntasEvaluacionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTestIdtest() == null ? 0 : this.getTestIdtest().hashCode() );
         result = 37 * result + ( getEvapreguntasPreguntaId() == null ? 0 : this.getEvapreguntasPreguntaId().hashCode() );
         result = 37 * result + ( getEvapreguntasEvaluacionId() == null ? 0 : this.getEvapreguntasEvaluacionId().hashCode() );
         return result;
   }   


}


