package model.entities;
// Generated 28-abr-2015 16:50:41 by Hibernate Tools 4.3.1



/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private RespuestaId id;
     private Evapreguntas evapreguntas;
     private Test test;
     private String respuesta;

    public Respuesta() {
    }

	
    public Respuesta(RespuestaId id, Evapreguntas evapreguntas, Test test) {
        this.id = id;
        this.evapreguntas = evapreguntas;
        this.test = test;
    }
    public Respuesta(RespuestaId id, Evapreguntas evapreguntas, Test test, String respuesta) {
       this.id = id;
       this.evapreguntas = evapreguntas;
       this.test = test;
       this.respuesta = respuesta;
    }
   
    public RespuestaId getId() {
        return this.id;
    }
    
    public void setId(RespuestaId id) {
        this.id = id;
    }
    public Evapreguntas getEvapreguntas() {
        return this.evapreguntas;
    }
    
    public void setEvapreguntas(Evapreguntas evapreguntas) {
        this.evapreguntas = evapreguntas;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }




}


