package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private TestId id;
     private Evaluacionpreguntas evaluacionpreguntas;
     private Encuestado encuestado;
     private char respuesta;

    public Test() {
    }

    public Test(TestId id, Evaluacionpreguntas evaluacionpreguntas, Encuestado encuestado, char respuesta) {
       this.id = id;
       this.evaluacionpreguntas = evaluacionpreguntas;
       this.encuestado = encuestado;
       this.respuesta = respuesta;
    }
   
    public TestId getId() {
        return this.id;
    }
    
    public void setId(TestId id) {
        this.id = id;
    }
    public Evaluacionpreguntas getEvaluacionpreguntas() {
        return this.evaluacionpreguntas;
    }
    
    public void setEvaluacionpreguntas(Evaluacionpreguntas evaluacionpreguntas) {
        this.evaluacionpreguntas = evaluacionpreguntas;
    }
    public Encuestado getEncuestado() {
        return this.encuestado;
    }
    
    public void setEncuestado(Encuestado encuestado) {
        this.encuestado = encuestado;
    }
    public char getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(char respuesta) {
        this.respuesta = respuesta;
    }




}


