package model.entities;
// Generated 23-11-2014 11:31:32 PM by Hibernate Tools 3.2.1.GA



/**
 * TestId generated by hbm2java
 */
public class TestId  implements java.io.Serializable {


     private int idEncuestado;
     private int idTest;

    public TestId() {
    }

    public TestId(int idEncuestado, int idTest) {
       this.idEncuestado = idEncuestado;
       this.idTest = idTest;
    }
   
    public int getIdEncuestado() {
        return this.idEncuestado;
    }
    
    public void setIdEncuestado(int idEncuestado) {
        this.idEncuestado = idEncuestado;
    }
    public int getIdTest() {
        return this.idTest;
    }
    
    public void setIdTest(int idTest) {
        this.idTest = idTest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TestId) ) return false;
		 TestId castOther = ( TestId ) other; 
         
		 return (this.getIdEncuestado()==castOther.getIdEncuestado())
 && (this.getIdTest()==castOther.getIdTest());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEncuestado();
         result = 37 * result + this.getIdTest();
         return result;
   }   


}


