package model.entities;
// Generated 14-may-2015 17:53:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private Integer idtest;
     private Evaluacion evaluacion;
     private Encuestado encuestado;
     private Set respuestas = new HashSet(0);

    public Test() {
    }

	
    public Test(Integer idtest, Evaluacion evaluacion, Encuestado encuestado) {
        this.idtest = idtest;
        this.evaluacion = evaluacion;
        this.encuestado = encuestado;
    }
    public Test(Integer idtest, Evaluacion evaluacion, Encuestado encuestado, Set respuestas) {
       this.idtest = idtest;
       this.evaluacion = evaluacion;
       this.encuestado = encuestado;
       this.respuestas = respuestas;
    }
   
    public Integer getIdtest() {
        return this.idtest;
    }
    
    public void setIdtest(Integer idtest) {
        this.idtest = idtest;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Encuestado getEncuestado() {
        return this.encuestado;
    }
    
    public void setEncuestado(Encuestado encuestado) {
        this.encuestado = encuestado;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


