package model.entities;
// Generated 27-may-2015 14:38:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * UserRolesId generated by hbm2java
 */
public class UserRolesId  implements java.io.Serializable {


     private Integer idencuestador;
     private String roleName;

    public UserRolesId() {
    }

    public UserRolesId(Integer idencuestador, String roleName) {
       this.idencuestador = idencuestador;
       this.roleName = roleName;
    }
   
    public Integer getIdencuestador() {
        return this.idencuestador;
    }
    
    public void setIdencuestador(Integer idencuestador) {
        this.idencuestador = idencuestador;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRolesId) ) return false;
		 UserRolesId castOther = ( UserRolesId ) other; 
         
		 return ( (this.getIdencuestador()==castOther.getIdencuestador()) || ( this.getIdencuestador()!=null && castOther.getIdencuestador()!=null && this.getIdencuestador().equals(castOther.getIdencuestador()) ) )
 && ( (this.getRoleName()==castOther.getRoleName()) || ( this.getRoleName()!=null && castOther.getRoleName()!=null && this.getRoleName().equals(castOther.getRoleName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdencuestador() == null ? 0 : this.getIdencuestador().hashCode() );
         result = 37 * result + ( getRoleName() == null ? 0 : this.getRoleName().hashCode() );
         return result;
   }   


}


