package model.entities;
// Generated 27-may-2015 14:38:52 by Hibernate Tools 4.3.1



/**
 * UserRoles generated by hbm2java
 */
public class UserRoles  implements java.io.Serializable {


     private UserRolesId id;
     private Encuestador encuestador;

    public UserRoles() {
    }

    public UserRoles(UserRolesId id, Encuestador encuestador) {
       this.id = id;
       this.encuestador = encuestador;
    }
   
    public UserRolesId getId() {
        return this.id;
    }
    
    public void setId(UserRolesId id) {
        this.id = id;
    }
    public Encuestador getEncuestador() {
        return this.encuestador;
    }
    
    public void setEncuestador(Encuestador encuestador) {
        this.encuestador = encuestador;
    }




}


