package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA



/**
 * Alumnoseccion generated by hbm2java
 */
public class Alumnoseccion  implements java.io.Serializable {


     private AlumnoseccionId id;
     private Alumno alumno;
     private Seccion seccion;

    public Alumnoseccion() {
    }

    public Alumnoseccion(AlumnoseccionId id, Alumno alumno, Seccion seccion) {
       this.id = id;
       this.alumno = alumno;
       this.seccion = seccion;
    }
   
    public AlumnoseccionId getId() {
        return this.id;
    }
    
    public void setId(AlumnoseccionId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }




}


