package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String rutAlumno;
     private Apoderado apoderado;
     private String primerNombre;
     private String apellidoPaterno;
     private String segundoNombre;
     private String apellidoMaterno;
     private Date fechaNacimiento;
     private String curso;
     private String sexo;
     private String direccion;
     private String fono;
     private String nivel;
     private Set gratises = new HashSet(0);
     private Set pagadas = new HashSet(0);
     private Set alumnoseccions = new HashSet(0);
     private Semestre semestre;

    public Semestre getSemestre() {
        return semestre;
    }

    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
     
     

    public Alumno() {
    }

	
    public Alumno(String rutAlumno, Apoderado apoderado, String primerNombre, String apellidoPaterno, String segundoNombre, String apellidoMaterno, Date fechaNacimiento, String curso, String sexo, String direccion, String fono, String nivel) {
        this.rutAlumno = rutAlumno;
        this.apoderado = apoderado;
        this.primerNombre = primerNombre;
        this.apellidoPaterno = apellidoPaterno;
        this.segundoNombre = segundoNombre;
        this.apellidoMaterno = apellidoMaterno;
        this.fechaNacimiento = fechaNacimiento;
        this.curso = curso;
        this.sexo = sexo;
        this.direccion = direccion;
        this.fono = fono;
        this.nivel = nivel;
    }
    public Alumno(String rutAlumno, Apoderado apoderado, String primerNombre, String apellidoPaterno, String segundoNombre, String apellidoMaterno, Date fechaNacimiento, String curso, String sexo, String direccion, String fono, String nivel, Set gratises, Set pagadas, Set alumnoseccions) {
       this.rutAlumno = rutAlumno;
       this.apoderado = apoderado;
       this.primerNombre = primerNombre;
       this.apellidoPaterno = apellidoPaterno;
       this.segundoNombre = segundoNombre;
       this.apellidoMaterno = apellidoMaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.curso = curso;
       this.sexo = sexo;
       this.direccion = direccion;
       this.fono = fono;
       this.nivel = nivel;
       this.gratises = gratises;
       this.pagadas = pagadas;
       this.alumnoseccions = alumnoseccions;
    }
   
    public String getRutAlumno() {
        return this.rutAlumno;
    }
    
    public void setRutAlumno(String rutAlumno) {
        this.rutAlumno = rutAlumno;
    }
    public Apoderado getApoderado() {
        return this.apoderado;
    }
    
    public void setApoderado(Apoderado apoderado) {
        this.apoderado = apoderado;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getFono() {
        return this.fono;
    }
    
    public void setFono(String fono) {
        this.fono = fono;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Set getGratises() {
        return this.gratises;
    }
    
    public void setGratises(Set gratises) {
        this.gratises = gratises;
    }
    public Set getPagadas() {
        return this.pagadas;
    }
    
    public void setPagadas(Set pagadas) {
        this.pagadas = pagadas;
    }
    public Set getAlumnoseccions() {
        return this.alumnoseccions;
    }
    
    public void setAlumnoseccions(Set alumnoseccions) {
        this.alumnoseccions = alumnoseccions;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Alumno other = (Alumno) obj;
        if ((this.rutAlumno == null) ? (other.rutAlumno != null) : !this.rutAlumno.equals(other.rutAlumno)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

   



}


