package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA



/**
 * AlumnoseccionId generated by hbm2java
 */
public class AlumnoseccionId  implements java.io.Serializable {


     private String rutAlumno;
     private String diaTaller;
     private int idTaller;
     private int codSeccion;

    public AlumnoseccionId() {
    }

    public AlumnoseccionId(String rutAlumno, String diaTaller, int idTaller, int codSeccion) {
       this.rutAlumno = rutAlumno;
       this.diaTaller = diaTaller;
       this.idTaller = idTaller;
       this.codSeccion = codSeccion;
    }
   
    public String getRutAlumno() {
        return this.rutAlumno;
    }
    
    public void setRutAlumno(String rutAlumno) {
        this.rutAlumno = rutAlumno;
    }
    public String getDiaTaller() {
        return this.diaTaller;
    }
    
    public void setDiaTaller(String diaTaller) {
        this.diaTaller = diaTaller;
    }
    public int getIdTaller() {
        return this.idTaller;
    }
    
    public void setIdTaller(int idTaller) {
        this.idTaller = idTaller;
    }
    public int getCodSeccion() {
        return this.codSeccion;
    }
    
    public void setCodSeccion(int codSeccion) {
        this.codSeccion = codSeccion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoseccionId) ) return false;
		 AlumnoseccionId castOther = ( AlumnoseccionId ) other; 
         
		 return ( (this.getRutAlumno()==castOther.getRutAlumno()) || ( this.getRutAlumno()!=null && castOther.getRutAlumno()!=null && this.getRutAlumno().equals(castOther.getRutAlumno()) ) )
 && ( (this.getDiaTaller()==castOther.getDiaTaller()) || ( this.getDiaTaller()!=null && castOther.getDiaTaller()!=null && this.getDiaTaller().equals(castOther.getDiaTaller()) ) )
 && (this.getIdTaller()==castOther.getIdTaller())
 && (this.getCodSeccion()==castOther.getCodSeccion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRutAlumno() == null ? 0 : this.getRutAlumno().hashCode() );
         result = 37 * result + ( getDiaTaller() == null ? 0 : this.getDiaTaller().hashCode() );
         result = 37 * result + this.getIdTaller();
         result = 37 * result + this.getCodSeccion();
         return result;
   }   


}


