package model.Entitys;
// Generated 15-03-2015 08:09:58 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cheque generated by hbm2java
 */
public class Cheque  implements java.io.Serializable {


     private Integer idCheque;
     private String banco;
     private String titular;
     private double monto;
     private String serie;
     private Date fechaPago;
     private Pago pago;

    public Cheque() {
    }

    public Cheque(Integer idCheque, String banco, String titular, double monto, String serie, Date fechaPago, Pago pago) {
        this.idCheque = idCheque;
        this.banco = banco;
        this.titular = titular;
        this.monto = monto;
        this.serie = serie;
        this.fechaPago = fechaPago;
        this.pago = pago;
    }

    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public Integer getIdCheque() {
        return this.idCheque;
    }
    
    public void setIdCheque(Integer idCheque) {
        this.idCheque = idCheque;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getTitular() {
        return this.titular;
    }
    
    public void setTitular(String titular) {
        this.titular = titular;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    public Pago getPago() {
        return pago;
    }

    public void setPago(Pago pago) {
        this.pago = pago;
    }





}


