package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Diasseccion generated by hbm2java
 */
public class Diasseccion  implements java.io.Serializable {


     private Integer idDiasSeccion;
     private Seccion seccion;
     private String horaInicio;
     private String horaFin;
     private String diaTaller;
     private String lugar;

    public Diasseccion() {
    }

    public Diasseccion(Seccion seccion, String horaInicio, String horaFin, String diaTaller, String lugar) {
       this.seccion = seccion;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.diaTaller = diaTaller;
       this.lugar = lugar;
    }
   
    public Integer getIdDiasSeccion() {
        return this.idDiasSeccion;
    }
    
    public void setIdDiasSeccion(Integer idDiasSeccion) {
        this.idDiasSeccion = idDiasSeccion;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

    public String getHoraFin() {
        return horaFin;
    }

    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }

    public String getHoraInicio() {
        return horaInicio;
    }

    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }
    
    
    public String getDiaTaller() {
        return this.diaTaller;
    }
    
    public void setDiaTaller(String diaTaller) {
        this.diaTaller = diaTaller;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }




}


