package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Gratis generated by hbm2java
 */
public class Gratis  implements java.io.Serializable {


     private GratisId id;
     private Semestre semestre;
     private Alumno alumno;
     private Taller taller;
     private Date inscripcionFechaInscripcion;
     private String numOrdenInscripcion;

    public Gratis() {
    }

    public Gratis(GratisId id, Semestre semestre, Alumno alumno, Taller taller, Date inscripcionFechaInscripcion, String numOrdenInscripcion) {
       this.id = id;
       this.semestre = semestre;
       this.alumno = alumno;
       this.taller = taller;
       this.inscripcionFechaInscripcion = inscripcionFechaInscripcion;
       this.numOrdenInscripcion = numOrdenInscripcion;
    }
   
    public GratisId getId() {
        return this.id;
    }
    
    public void setId(GratisId id) {
        this.id = id;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }
    public Date getInscripcionFechaInscripcion() {
        return this.inscripcionFechaInscripcion;
    }
    
    public void setInscripcionFechaInscripcion(Date inscripcionFechaInscripcion) {
        this.inscripcionFechaInscripcion = inscripcionFechaInscripcion;
    }
    public String getNumOrdenInscripcion() {
        return this.numOrdenInscripcion;
    }
    
    public void setNumOrdenInscripcion(String numOrdenInscripcion) {
        this.numOrdenInscripcion = numOrdenInscripcion;
    }




}


