package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA



/**
 * GratisId generated by hbm2java
 */
public class GratisId  implements java.io.Serializable {


     private String inscripcionRutAlumno;
     private int gratisIdTaller;
     private int semestreIdsemestre;

    public GratisId() {
    }

    public GratisId(String inscripcionRutAlumno, int gratisIdTaller, int semestreIdsemestre) {
       this.inscripcionRutAlumno = inscripcionRutAlumno;
       this.gratisIdTaller = gratisIdTaller;
       this.semestreIdsemestre = semestreIdsemestre;
    }
   
    public String getInscripcionRutAlumno() {
        return this.inscripcionRutAlumno;
    }
    
    public void setInscripcionRutAlumno(String inscripcionRutAlumno) {
        this.inscripcionRutAlumno = inscripcionRutAlumno;
    }
    public int getGratisIdTaller() {
        return this.gratisIdTaller;
    }
    
    public void setGratisIdTaller(int gratisIdTaller) {
        this.gratisIdTaller = gratisIdTaller;
    }
    public int getSemestreIdsemestre() {
        return this.semestreIdsemestre;
    }
    
    public void setSemestreIdsemestre(int semestreIdsemestre) {
        this.semestreIdsemestre = semestreIdsemestre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GratisId) ) return false;
		 GratisId castOther = ( GratisId ) other; 
         
		 return ( (this.getInscripcionRutAlumno()==castOther.getInscripcionRutAlumno()) || ( this.getInscripcionRutAlumno()!=null && castOther.getInscripcionRutAlumno()!=null && this.getInscripcionRutAlumno().equals(castOther.getInscripcionRutAlumno()) ) )
 && (this.getGratisIdTaller()==castOther.getGratisIdTaller())
 && (this.getSemestreIdsemestre()==castOther.getSemestreIdsemestre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInscripcionRutAlumno() == null ? 0 : this.getInscripcionRutAlumno().hashCode() );
         result = 37 * result + this.getGratisIdTaller();
         result = 37 * result + this.getSemestreIdsemestre();
         return result;
   }   


}


