package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Institucion generated by hbm2java
 */
public class Institucion  implements java.io.Serializable {


     private String rutInstitucion;
     private String nombre;
     private Set tallers = new HashSet(0);
     private Set tipoTallers = new HashSet(0);
     private Set semestres = new HashSet(0);

    public Institucion() {
    }

	
    public Institucion(String rutInstitucion, String nombre) {
        this.rutInstitucion = rutInstitucion;
        this.nombre = nombre;
    }
    public Institucion(String rutInstitucion, String nombre, Set tallers, Set tipoTallers, Set semestres) {
       this.rutInstitucion = rutInstitucion;
       this.nombre = nombre;
       this.tallers = tallers;
       this.tipoTallers = tipoTallers;
       this.semestres = semestres;
    }
   
    public String getRutInstitucion() {
        return this.rutInstitucion;
    }
    
    public void setRutInstitucion(String rutInstitucion) {
        this.rutInstitucion = rutInstitucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTallers() {
        return this.tallers;
    }
    
    public void setTallers(Set tallers) {
        this.tallers = tallers;
    }
    public Set getTipoTallers() {
        return this.tipoTallers;
    }
    
    public void setTipoTallers(Set tipoTallers) {
        this.tipoTallers = tipoTallers;
    }
    public Set getSemestres() {
        return this.semestres;
    }
    
    public void setSemestres(Set semestres) {
        this.semestres = semestres;
    }




}


