package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA



/**
 * PagadaId generated by hbm2java
 */
public class PagadaId  implements java.io.Serializable {


     private String inscripcionRutAlumno;
     private int pagadaIdTaller;
     private int semestreIdsemestre;

    public PagadaId() {
    }

    public PagadaId(String inscripcionRutAlumno, int pagadaIdTaller, int semestreIdsemestre) {
       this.inscripcionRutAlumno = inscripcionRutAlumno;
       this.pagadaIdTaller = pagadaIdTaller;
       this.semestreIdsemestre = semestreIdsemestre;
    }
   
    public String getInscripcionRutAlumno() {
        return this.inscripcionRutAlumno;
    }
    
    public void setInscripcionRutAlumno(String inscripcionRutAlumno) {
        this.inscripcionRutAlumno = inscripcionRutAlumno;
    }
    public int getPagadaIdTaller() {
        return this.pagadaIdTaller;
    }
    
    public void setPagadaIdTaller(int pagadaIdTaller) {
        this.pagadaIdTaller = pagadaIdTaller;
    }
    public int getSemestreIdsemestre() {
        return this.semestreIdsemestre;
    }
    
    public void setSemestreIdsemestre(int semestreIdsemestre) {
        this.semestreIdsemestre = semestreIdsemestre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagadaId) ) return false;
		 PagadaId castOther = ( PagadaId ) other; 
         
		 return ( (this.getInscripcionRutAlumno()==castOther.getInscripcionRutAlumno()) || ( this.getInscripcionRutAlumno()!=null && castOther.getInscripcionRutAlumno()!=null && this.getInscripcionRutAlumno().equals(castOther.getInscripcionRutAlumno()) ) )
 && (this.getPagadaIdTaller()==castOther.getPagadaIdTaller())
 && (this.getSemestreIdsemestre()==castOther.getSemestreIdsemestre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInscripcionRutAlumno() == null ? 0 : this.getInscripcionRutAlumno().hashCode() );
         result = 37 * result + this.getPagadaIdTaller();
         result = 37 * result + this.getSemestreIdsemestre();
         return result;
   }   


}


