package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idPago;
     private Formapago formapago;
     private BigDecimal montoPago;
     private Date fechaPago;
     private Set pagadas = new HashSet(0);
     private String serie;
     private String banco;
     private String titular;
     private Set cheques = new HashSet(0);
     
            

    public Pago() {
    }

	
    public Pago(int idPago, Formapago formapago, BigDecimal montoPago, Date fechaPago) {
        this.idPago = idPago;
        this.formapago = formapago;
        this.montoPago = montoPago;
        this.fechaPago = fechaPago;
    }
    public Pago(int idPago, Formapago formapago, BigDecimal montoPago, Date fechaPago, Set pagadas) {
       this.idPago = idPago;
       this.formapago = formapago;
       this.montoPago = montoPago;
       this.fechaPago = fechaPago;
       this.pagadas = pagadas;
    }

    public String getBanco() {
        return banco;
    }

    public void setBanco(String banco) {
        this.banco = banco;
    }

    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public String getTitular() {
        return titular;
    }

    public void setTitular(String titular) {
        this.titular = titular;
    }
   
    
    
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public Formapago getFormapago() {
        return this.formapago;
    }
    
    public void setFormapago(Formapago formapago) {
        this.formapago = formapago;
    }
    public BigDecimal getMontoPago() {
        return this.montoPago;
    }
    
    public void setMontoPago(BigDecimal montoPago) {
        this.montoPago = montoPago;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public Set getPagadas() {
        return this.pagadas;
    }
    
    public void setPagadas(Set pagadas) {
        this.pagadas = pagadas;
    }

    public Set getCheques() {
        return cheques;
    }

    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }




}


