package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private String idProfesor;
     private TipoTaller tipoTaller;
     private String nombreProfesor;
     private String apellidoProfesor;
     private Set seccionprofesors = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(String idProfesor, TipoTaller tipoTaller, String nombreProfesor, String apellidoProfesor) {
        this.idProfesor = idProfesor;
        this.tipoTaller = tipoTaller;
        this.nombreProfesor = nombreProfesor;
        this.apellidoProfesor = apellidoProfesor;
    }
    public Profesor(String idProfesor, TipoTaller tipoTaller, String nombreProfesor, String apellidoProfesor, Set seccionprofesors) {
       this.idProfesor = idProfesor;
       this.tipoTaller = tipoTaller;
       this.nombreProfesor = nombreProfesor;
       this.apellidoProfesor = apellidoProfesor;
       this.seccionprofesors = seccionprofesors;
    }
   
    public String getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(String idProfesor) {
        this.idProfesor = idProfesor;
    }
    public TipoTaller getTipoTaller() {
        return this.tipoTaller;
    }
    
    public void setTipoTaller(TipoTaller tipoTaller) {
        this.tipoTaller = tipoTaller;
    }
    public String getNombreProfesor() {
        return this.nombreProfesor;
    }
    
    public void setNombreProfesor(String nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }
    public String getApellidoProfesor() {
        return this.apellidoProfesor;
    }
    
    public void setApellidoProfesor(String apellidoProfesor) {
        this.apellidoProfesor = apellidoProfesor;
    }
    public Set getSeccionprofesors() {
        return this.seccionprofesors;
    }
    
    public void setSeccionprofesors(Set seccionprofesors) {
        this.seccionprofesors = seccionprofesors;
    }




}


