package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA



/**
 * SeccionprofesorId generated by hbm2java
 */
public class SeccionprofesorId  implements java.io.Serializable {


     private String seccionDiaTaller;
     private int seccionIdTaller;
     private int seccionCodSeccion;
     private String profesorIdProfesor;

    public SeccionprofesorId() {
    }

    public SeccionprofesorId(String seccionDiaTaller, int seccionIdTaller, int seccionCodSeccion, String profesorIdProfesor) {
       this.seccionDiaTaller = seccionDiaTaller;
       this.seccionIdTaller = seccionIdTaller;
       this.seccionCodSeccion = seccionCodSeccion;
       this.profesorIdProfesor = profesorIdProfesor;
    }
   
    public String getSeccionDiaTaller() {
        return this.seccionDiaTaller;
    }
    
    public void setSeccionDiaTaller(String seccionDiaTaller) {
        this.seccionDiaTaller = seccionDiaTaller;
    }
    public int getSeccionIdTaller() {
        return this.seccionIdTaller;
    }
    
    public void setSeccionIdTaller(int seccionIdTaller) {
        this.seccionIdTaller = seccionIdTaller;
    }
    public int getSeccionCodSeccion() {
        return this.seccionCodSeccion;
    }
    
    public void setSeccionCodSeccion(int seccionCodSeccion) {
        this.seccionCodSeccion = seccionCodSeccion;
    }
    public String getProfesorIdProfesor() {
        return this.profesorIdProfesor;
    }
    
    public void setProfesorIdProfesor(String profesorIdProfesor) {
        this.profesorIdProfesor = profesorIdProfesor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeccionprofesorId) ) return false;
		 SeccionprofesorId castOther = ( SeccionprofesorId ) other; 
         
		 return ( (this.getSeccionDiaTaller()==castOther.getSeccionDiaTaller()) || ( this.getSeccionDiaTaller()!=null && castOther.getSeccionDiaTaller()!=null && this.getSeccionDiaTaller().equals(castOther.getSeccionDiaTaller()) ) )
 && (this.getSeccionIdTaller()==castOther.getSeccionIdTaller())
 && (this.getSeccionCodSeccion()==castOther.getSeccionCodSeccion())
 && ( (this.getProfesorIdProfesor()==castOther.getProfesorIdProfesor()) || ( this.getProfesorIdProfesor()!=null && castOther.getProfesorIdProfesor()!=null && this.getProfesorIdProfesor().equals(castOther.getProfesorIdProfesor()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSeccionDiaTaller() == null ? 0 : this.getSeccionDiaTaller().hashCode() );
         result = 37 * result + this.getSeccionIdTaller();
         result = 37 * result + this.getSeccionCodSeccion();
         result = 37 * result + ( getProfesorIdProfesor() == null ? 0 : this.getProfesorIdProfesor().hashCode() );
         return result;
   }   


}


