package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA



/**
 * Seccionprofesor generated by hbm2java
 */
public class Seccionprofesor  implements java.io.Serializable {


     private SeccionprofesorId id;
     private Seccion seccion;
     private Profesor profesor;

    public Seccionprofesor() {
    }

    public Seccionprofesor(SeccionprofesorId id, Seccion seccion, Profesor profesor) {
       this.id = id;
       this.seccion = seccion;
       this.profesor = profesor;
    }
   
    public SeccionprofesorId getId() {
        return this.id;
    }
    
    public void setId(SeccionprofesorId id) {
        this.id = id;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }




}


