package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private Integer codSeccion;
     private Taller taller;
     private int cupos;
     private String nombreSeccion;
     private Set diasseccions = new HashSet(0);
     private Set seccionprofesors = new HashSet(0);
     private Set alumnoseccions = new HashSet(0);
     private String[] listaProfesores;
     private int inscritos;

    public int getInscritos() {
        return inscritos;
    }

    public void setInscritos(int inscritos) {
        this.inscritos = inscritos;
    }

 

    public Seccion() {
    }

    public String[] getListaProfesores() {
        return listaProfesores;
    }

    public void setListaProfesores(String[] listaProfesores) {
        this.listaProfesores = listaProfesores;
    }

    
    
	
    public Seccion(Taller taller, int cupos, String nombreSeccion) {
        this.taller = taller;
        this.cupos = cupos;
        this.nombreSeccion = nombreSeccion;
    }
    public Seccion(Taller taller, int cupos, String nombreSeccion, Set diasseccions, Set seccionprofesors, Set alumnoseccions) {
       this.taller = taller;
       this.cupos = cupos;
       this.nombreSeccion = nombreSeccion;
       this.diasseccions = diasseccions;
       this.seccionprofesors = seccionprofesors;
       this.alumnoseccions = alumnoseccions;
    }
   
    public Integer getCodSeccion() {
        return this.codSeccion;
    }
    
    public void setCodSeccion(Integer codSeccion) {
        this.codSeccion = codSeccion;
    }
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }
    public int getCupos() {
        return this.cupos;
    }
    
    public void setCupos(int cupos) {
        this.cupos = cupos;
    }
    public String getNombreSeccion() {
        return this.nombreSeccion;
    }
    
    public void setNombreSeccion(String nombreSeccion) {
        this.nombreSeccion = nombreSeccion;
    }
    public Set getDiasseccions() {
        return this.diasseccions;
    }
    
    public void setDiasseccions(Set diasseccions) {
        this.diasseccions = diasseccions;
    }
    public Set getSeccionprofesors() {
        return this.seccionprofesors;
    }
    
    public void setSeccionprofesors(Set seccionprofesors) {
        this.seccionprofesors = seccionprofesors;
    }
    public Set getAlumnoseccions() {
        return this.alumnoseccions;
    }
    
    public void setAlumnoseccions(Set alumnoseccions) {
        this.alumnoseccions = alumnoseccions;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seccion other = (Seccion) obj;
        if (this.codSeccion != other.codSeccion && (this.codSeccion == null || !this.codSeccion.equals(other.codSeccion))) {
            return false;
        }
        if (this.taller != other.taller && (this.taller == null || !this.taller.equals(other.taller))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + (this.codSeccion != null ? this.codSeccion.hashCode() : 0);
        hash = 19 * hash + (this.taller != null ? this.taller.hashCode() : 0);
        return hash;
    }

    



}


