package model.Entitys;
// Generated 07-07-2014 01:00:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTaller generated by hbm2java
 */
public class TipoTaller  implements java.io.Serializable {


     private Integer idTipoTaller;
     private Institucion institucion;
     private String nombre;
     
     private Set profesors = new HashSet(0);
     private Set tallers = new HashSet(0);

    public TipoTaller() {
    }

    
	
    public TipoTaller(Institucion institucion, String nombre) {
        this.institucion = institucion;
        this.nombre = nombre;
    }
    public TipoTaller(Institucion institucion, String nombre, Set profesors, Set tallers) {
       this.institucion = institucion;
       this.nombre = nombre;
       this.profesors = profesors;
       this.tallers = tallers;
    }
   
    public Integer getIdTipoTaller() {
        return this.idTipoTaller;
    }
    
    public void setIdTipoTaller(Integer idTipoTaller) {
        this.idTipoTaller = idTipoTaller;
    }
    public Institucion getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(Institucion institucion) {
        this.institucion = institucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }
    public Set getTallers() {
        return this.tallers;
    }
    
    public void setTallers(Set tallers) {
        this.tallers = tallers;
    }




}


