package model.Entitys;
// Generated 22-06-2014 12:47:50 AM by Hibernate Tools 3.2.1.GA



/**
 * UserRoles generated by hbm2java
 */
public class UserRoles  implements java.io.Serializable {


     private long userRoleId;
     private Users users;
     private String authority;

    public UserRoles() {
    }

    public UserRoles(long userRoleId, Users users, String authority) {
       this.userRoleId = userRoleId;
       this.users = users;
       this.authority = authority;
    }
   
    public long getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(long userRoleId) {
        this.userRoleId = userRoleId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UserRoles other = (UserRoles) obj;
        if (this.users != other.users && (this.users == null || !this.users.equals(other.users))) {
            return false;
        }
        if ((this.authority == null) ? (other.authority != null) : !this.authority.equals(other.authority)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 71 * hash + (this.users != null ? this.users.hashCode() : 0);
        hash = 71 * hash + (this.authority != null ? this.authority.hashCode() : 0);
        return hash;
    }




}


